Unit testing
swetha-gangu/STEP_Internship pull request #4
Opened 2020-06-17 20:08 UTC by swetha-gangu

2020-06-18 18:48 UTC, vikshanker reviewed
Are the tests in a different commit?

2020-06-18 18:48 UTC, v1shanker commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +        String userEmail = "";
nit: String userEmail;

you don't need to assign it a value here since that value is useless in both branches.

2020-06-18 18:48 UTC, v1shanker commented on portfolio/src/main/java/com/google/sps/servlets/LoginStatusServlet.java
> +            String urlToRedirectToAfterUserLogsOut = "/index.html";
nit: you can call this logoutRedirectUrl

2020-06-18 18:48 UTC, v1shanker commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +        if (!eventHasAttendee(attendees, curr_event)) return last_event;
please uses braces and put the return on the next line even if its only one line. its less error prone in the future.

2020-06-18 18:48 UTC, v1shanker commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +        if (curr_range.overlaps(last_range)) return getLaterTime(curr_event, last_event);
same here

2020-06-18 18:48 UTC, v1shanker commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +        else{
space between else and bracket

2020-06-18 18:48 UTC, v1shanker commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +    private static final Comparator<Event> ORDER_BY_START = new Comparator<Event>() {
this variable should be at the top of the file.

2020-06-18 19:51 UTC, swetha-gangu commented
> Are the tests in a different commit?

Yes.

2020-06-19 05:35 UTC, vikshanker requested changes

2020-06-19 05:35 UTC, v1shanker commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +        String userEmail = "";
you resolved the comment but didn't address it in the code.

2020-06-19 05:35 UTC, v1shanker commented on portfolio/src/main/java/com/google/sps/servlets/LoginStatusServlet.java
> +            String urlToRedirectToAfterUserLogsOut = "/index.html";
again you resolved the comment but didnt address it in the code or with a reply.

2020-06-19 05:35 UTC, v1shanker commented on walkthroughs/week-5-tdd/project/src/test/java/com/google/sps/FindMeetingQueryTest.java
> +
remove blank lines in the middle of the act block. here and below.

2020-06-19 14:57 UTC, swetha-gangu commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +        String userEmail = "";
It was in my most recent commit.

2020-06-19 14:57 UTC, swetha-gangu commented on portfolio/src/main/java/com/google/sps/servlets/LoginStatusServlet.java
> +            String urlToRedirectToAfterUserLogsOut = "/index.html";
Was in most recent commit.

2020-06-19 23:22 UTC, vikshanker approved these changes

2020-06-19 23:22 UTC, v1shanker commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +            System.out.printf("score : %.2f", score);
remove

2020-06-19 23:22 UTC, v1shanker commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +        System.out.printf("score : %.2f", score);
remove

2020-06-19 23:22 UTC, v1shanker commented on portfolio/src/main/webapp/script.js
> +            console.log(comment.score);
either remove or make the message useful to devs

2020-06-19 23:22 UTC, v1shanker commented on walkthroughs/week-5-tdd/intro/src/test/java/com/google/sps/GreeterTest.java
> +        // Whitespace should be trimmed
the comment is extraneous.

2020-06-19 23:22 UTC, v1shanker commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +            int first_start = first.getWhen().start();
use camelCase everywhere

2020-06-22 21:04 UTC, merged